apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: s2i
  labels:
    app: backend
spec:
  replicas: 0 # Managed by KEDA
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/aihpi/sketch2image-backend:latest
        imagePullPolicy: IfNotPresent # Optimize to prevent expired PAT registry issues
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "0"
        - name: DEVICE
          value: cuda
        - name: HOST
          value: 0.0.0.0
        - name: PORT
          value: "8000"
        - name: DEBUG_MODE
          value: "false"
        - name: DEFAULT_MODEL_ID
          value: t2i_adapter_sdxl
        - name: NUM_INFERENCE_STEPS
          value: "40"
        - name: GUIDANCE_SCALE
          value: "7.5"
        - name: OUTPUT_IMAGE_SIZE
          value: "512"
        - name: PUBLIC_URL
          value: https://s2i.aisc.hpi.de
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: huggingface-token
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /app/dataset
          name: dataset-storage
        - mountPath: /root/.cache/huggingface
          name: huggingface-cache
      imagePullSecrets:
      - name: ghcr-secret
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-A30
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      volumes:
      - name: dataset-storage
        persistentVolumeClaim:
          claimName: backend-dataset-pvc
      - name: huggingface-cache
        persistentVolumeClaim:
          claimName: huggingface-cache-pvc
