apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: s2i
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: backend-proxy
  type: ClusterIP
